### ISSUE TITLE
Where is the bounding box information of the MTFL dataset?

### ISSUE THREAD

**Issue by mariolew** [zhzhanp/TCDCN-face-alignment#2]
The annotations are only landmarks and attributes but no bounding box information.

**Comment by zhzhanp** [comment]
You can easily generate the bounding box based on the landmarks.

**Comment by mariolew** [comment]
Would you mind giving me an example on how you generate bounding box for TCDCN?

**Comment by zhzhanp** [comment]
Below is the pseudocode that can generate the bounding box. You may need to tune the size/scale of the bounding box for best performance for you data on hand.

pt_x = [facedata.pts.LeftEyeCenter(1) facedata.pts.RightEyeCenter(1) facedata.pts.NoseCenter(1)...
            facedata.pts.MouthLeftCorner(1) facedata.pts.MouthRightCorner(1)];
pt_y = [facedata.pts.LeftEyeCenter(2) facedata.pts.RightEyeCenter(2) facedata.pts.NoseCenter(2)...
            facedata.pts.MouthLeftCorner(2) facedata.pts.MouthRightCorner(2)];
centerx = mean(pt_x(:));centery = mean(pt_y(:));
l1 = sqrt((pt_x(1)-pt_x(2)).^2+(pt_y(1)-pt_y(2)).^2);
l2 = sqrt((pt_x(1)-pt_x(4)).^2+(pt_y(1)-pt_y(4)).^2);
sz = max([abs(l1),abs(l2)]);
box1=[centerx-sz/2,centery-sz/2,sz,sz];
box1 = round(bbApply('resize', box1, 2, 2))+1;
